#!/bin/bash

env=${1}

echo "Install dependencies..."
npm install

# Compiling sources
ng build --configuration=${env}

# Copying compiling files to web
sudo rm -rf /usr/share/nginx/html/*
cp -r ./dist/linovhr-admin-ui/* /var/www/html/*