import { ModuleWithProviders, NgModule } from '@angular/core';
import {
    AutoCompleteModule,
    AccordionModule,
    ButtonModule,
    BreadcrumbModule,
    BlockUIModule,
    CalendarModule,
    CaptchaModule,
    CarouselModule,
    ChartModule,
    CheckboxModule,
    ConfirmDialogModule,
    ConfirmationService,
    DataListModule,
    DataScrollerModule,
    DeferModule,
    DialogModule,
    DragDropModule,
    DropdownModule,
    FieldsetModule,
    EditorModule,
    FileUploadModule,
    GrowlModule,
    InputMaskModule,
    InputSwitchModule,
    InputTextareaModule,
    InputTextModule,
    ListboxModule,
    MenuModule,
    MessageModule,
    MessagesModule,
    MultiSelectModule,
    OrderListModule,
    OrganizationChartModule,
    OverlayPanelModule,
    PaginatorModule,
    PanelModule,
    PanelMenuModule,
    PickListModule,
    ProgressBarModule,
    ProgressSpinnerModule,
    RadioButtonModule,
    ScheduleModule,
    SelectButtonModule,
    SidebarModule,
    SliderModule,
    SpinnerModule,
    SplitButtonModule,
    StepsModule,
    TabMenuModule,
    TabViewModule,
    TieredMenuModule,
    ToggleButtonModule,
    TooltipModule,
    TreeModule,
    TreeTableModule,
    CardModule,
    ScrollPanelModule,
    ToolbarModule,
    ChipsModule,
} from 'primeng/primeng';
import { PrimeFormatPipeModule } from './pipe/prime-format/prime-format-pipe.module';
import { ToastModule } from 'primeng/toast';
import { TableModule } from 'primeng/table';
import { FullCalendarModule } from 'primeng/fullcalendar';
import { DataViewModule } from 'primeng/dataview';
import { DynamicDialogModule } from 'primeng/dynamicdialog';

/**
 *  Export and providers only for PRIME
 */
@NgModule({
    imports: [],
    providers: [ConfirmationService],
    exports: [
        AccordionModule,
        AutoCompleteModule,
        BreadcrumbModule,
        ButtonModule,
        BlockUIModule,
        CalendarModule,
        CaptchaModule,
        CarouselModule,
        ChipsModule,
        ChartModule,
        CheckboxModule,
        ConfirmDialogModule,
        DeferModule,
        DragDropModule,
        DataListModule,
        EditorModule,
        DataScrollerModule,
        DialogModule,
        DropdownModule,
        FieldsetModule,
        FileUploadModule,
        GrowlModule,
        InputMaskModule,
        InputSwitchModule,
        InputTextareaModule,
        InputTextModule,
        ListboxModule,
        MenuModule,
        MessageModule,
        MessagesModule,
        MultiSelectModule,
        OrderListModule,
        OrganizationChartModule,
        OverlayPanelModule,
        PanelModule,
        PanelMenuModule,
        PaginatorModule,
        PickListModule,
        ProgressBarModule,
        ProgressSpinnerModule,
        RadioButtonModule,
        ScheduleModule,
        SelectButtonModule,
        SidebarModule,
        SliderModule,
        StepsModule,
        SpinnerModule,
        SplitButtonModule,
        TabMenuModule,
        TableModule,
        TabViewModule,
        TieredMenuModule,
        ToastModule,
        ToggleButtonModule,
        TooltipModule,
        TreeModule,
        PrimeFormatPipeModule, // custom pipe for prime components
        FullCalendarModule,
        DataViewModule,
        TreeTableModule,
        CardModule,
        ScrollPanelModule,
        ToolbarModule,
        DynamicDialogModule,
    ],
})
export class PrimeAppModule {
    static forRoot(): ModuleWithProviders {
        return {
            ngModule: PrimeAppModule,
        };
    }
}
